// priority: 0

console.info('Registering KJS Fluids...')

onEvent('fluid.registry', event => {
	event.create("molten_iron_quartz")	.thickTexture(0xdedede)	.bucketColor(0xdedede)	.displayName("Molten Quartz Enriched Iron")		.noBlock() 
	event.create("andesite_alloy")		.thickTexture(0x669999)	.bucketColor(0x669999)	.displayName("Molten Andesite Alloy")			.noBlock()
	event.create("andesite_stone")		.thickTexture(0x666666)	.bucketColor(0x666666)	.displayName("Molten Andesite Stone")			.noBlock()
	event.create("purified_water")		.thinTexture(0x003366)	.bucketColor(0x003366)	.displayName("Purified Water")					.noBlock()
	event.create("boiled_water")		.thinTexture(0x6699cc)	.bucketColor(0x6699cc)	.displayName("Boiled Water")					.noBlock()
	event.create("herbal_water")		.thinTexture(0x336666)	.bucketColor(0x336666)	.displayName("Herbal Water")					.noBlock()
	event.create("mineral_water")		.thinTexture(0x3399ff)	.bucketColor(0x3399ff)	.displayName("Mineral Water")					.noBlock()
	event.create("active_redstone")		.thinTexture(0xcc0000)	.bucketColor(0xcc0000)	.displayName("Active Molten Redstone")			.noBlock()
	event.create("seed_oil_water")		.thinTexture(0x936e52)	.bucketColor(0x936e52)	.displayName("Tree Seed Oil Water")				.noBlock() 
	event.create("goat_milk_vinegar")	.thinTexture(0xcbd4d6)	.bucketColor(0xcbd4d6)	.displayName("Goat Milk Vinegar")				.noBlock()
	event.create("yak_milk_vinegar")	.thinTexture(0xf2efe1)	.bucketColor(0xf2efe1)	.displayName("Yak Milk Vinegar")				.noBlock()
	event.create("oat_slurry")			.thinTexture(0xe7e0c8)	.bucketColor(0xe7e0c8)	.displayName("Oat Slurry")						.noBlock()
	event.create("lumpy_oat_milk")		.thinTexture(0xeae0c5)	.bucketColor(0xeae0c5)	.displayName("Lumpy Oat Milk")					.noBlock()
	event.create("unsweetened_oat_milk").thinTexture(0xebe2c7)	.bucketColor(0xebe2c7)	.displayName("Unsweetened Oat Milk")			.noBlock()
	event.create("oat_milk")			.thinTexture(0xebe2ca)	.bucketColor(0xebe2ca)	.displayName("Oat Milk")						.noBlock()
	event.create("bourbon")             .thinTexture(0xb7621b)  .bucketColor(0xb7621b)  .displayName("Bourbon")                         .noBlock()
	event.create("lager")               .thinTexture(0xcd8d4e)  .bucketColor(0xcd8d4e)  .displayName("Lager")                           .noBlock()
	event.create("chocolate_milk")      .thinTexture(0x755944)  .bucketColor(0x755944)  .displayName("Chocolate Milk")                  .noBlock()
	event.create("strawberry_milk")     .thinTexture(0xd46874)  .bucketColor(0xd46874)  .displayName("Strawberry Milk")                 .noBlock()
	event.create("cream_soda")          .thinTexture(0xd49368)  .bucketColor(0xd49368)  .displayName("Cream Soda")                      .noBlock()
	event.create("lemonade")            .thinTexture(0xf2e26b)  .bucketColor(0xf2e26b)  .displayName("Lemonade")                        .noBlock()
	event.create("flavored_lemonade")   .thinTexture(0xff7888)  .bucketColor(0xff7888)  .displayName("Flavored Lemonade")               .noBlock()
	event.create("fruit_juice")         .thinTexture(0xe67255)  .bucketColor(0xe67255)  .displayName("Fruit Juice")                     .noBlock()
	event.create("fruity_soda")         .thinTexture(0xe3502b)  .bucketColor(0xe3502b)  .displayName("Fruity Soda")                     .noBlock()
	event.create("veggie_juice")        .thinTexture(0xe36f2b)  .bucketColor(0xe36f2b)  .displayName("Vegetable Juice")                 .noBlock()
	event.create("veggie_soda")         .thinTexture(0xe05b0d)  .bucketColor(0xe05b0d)  .displayName("Vegetable Soda")                  .noBlock()
	event.create("builders_tea")        .thinTexture(0xcd7559)  .bucketColor(0xcd7559)  .displayName("Builder's Tea")                   .noBlock()
})
